import AXModel

print("AXModel")
test("protocol version is declared") { try expectEqual(protocolVersion, 1) }

runElementTests()
runIdRegistryTests()
runSnapshotTests()
runFormatterTests()
runDifferTests()
runDispatcherTests()
runBaselineTests()
runDesktopReachTests()
runCrossSpaceTests()
runSettleTests()
runEscapeSettleTests()
runWindowCountTests()
runScreenshotTests()
runRefusedActionTests()
runRefindTests()
runUnresponsiveHintTests()
runParkedRaiseTests()
runRepeatTests()
runKeyAndPointerTests()
runFigmaCostTests()
runSettleFlagTests()
runVerifyTests()
runWindowChoiceTests()
runTypeTests()
runServerTests()

finish()
